events with natural number and 0 as number of spots and with positive…
KatarzynaSzydlowska/event-manage pull request #9
Opened 2017-12-13 16:01 UTC by dodek08

… price

2017-12-14 21:32 UTC, KonradWadas approved these changes

2017-12-14 21:35 UTC, KonradWadas requested changes

2017-12-14 21:35 UTC, KonradWadas commented on cosine/tests.py
> +        self.assertTrue(!form.is_valid())
Use "not". Or evan better assertFalse.

2018-01-01 20:23 UTC, KonradWadas commented
Testy nadal nie dzialają, trzeba dociągnąć kod z mastera do twojej gałęzi. Wtedy zobaczymy czy testy smigaja i jak coverage, i sie zmergeuje :)

2018-01-03 15:39 UTC, dodek08 commented
fix'd

2018-01-03 22:27 UTC, KonradWadas approved these changes

2018-01-05 18:02 UTC, merged